spring.application.name=emergency-toilet
toilet.csv.path=src/main/resources/data/toilet.csv

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

firebase.credentials.path=firebase-service-account.json

seoul.api.key=647944645373616835364770595768
seoul.api.base-url=http://openapi.seoul.go.kr:8088